Remove extraineous debug tags for ansilble playbook.

diff --git a/ansible/roles/jannahio.end2end/molecule/default/tasks/converge/deploy_to_macos_docker_desktop.yml b/ansible/roles/jannahio.end2end/molecule/default/tasks/converge/deploy_to_macos_docker_desktop.yml
--- a/ansible/roles/jannahio.end2end/molecule/default/tasks/converge/deploy_to_macos_docker_desktop.yml
+++ b/ansible/roles/jannahio.end2end/molecule/default/tasks/converge/deploy_to_macos_docker_desktop.yml
@@ -1,9 +1,32 @@
 ---
+# # while ! ${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize/kustomize build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done;
 - name: "Deploy Operator to MacOs Docker Desktop"
   block:
-    - name: "Kubeflow install"
+    - name: "Kubeflow install (standlone deployment)"
       shell: |
-        while ! ${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize/kustomize build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done;
+        echo "standlone deployment"
+      when: {{ Jannah.stages.bootstrap.deploy }} == "standalone"
+      args:
+        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeflow/manifests"
+      tags:
+        - "docker_desktop_infra"
+        - "molecule_converge"
+        - "operator_e2e"
+        - "standalone_implementation"
+    - name: "Kubeflow install (local deployment)"
+      shell: |
+        echo "local deployment"
+      when: {{ Jannah.stages.bootstrap.deploy }} == "local"
+      args:
+        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeflow/manifests"
+      tags:
+        - "docker_desktop_infra"
+        - "molecule_converge"
+        - "operator_e2e"
+    - name: "Kubeflow install (full deployment)"
+      shell: |
+         echo "full deployment"
+      when: { { Jannah.stages.bootstrap.deploy } } == "full"
       args:
         chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeflow/manifests"
       tags:
@@ -101,7 +124,6 @@
         - "build_frontend_images"
         - "molecule_cleanup"
         - "operator_e2e"
-        - "dev_debug"
     - name: "Docker run jallohmediabuild/jannah-streamos-frontend-web-amd64"
       shell: |
         docker run --name jannah-streamos-frontend-web-amd64 -d jallohmediabuild/jannah-streamos-frontend-web-amd64:v0.0.1;
